# Generated by Django 5.1 on 2024-08-19 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Techniques_Library', '0002_initial'),
        ('Training_Plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='followers',
            field=models.ManyToManyField(related_name='followed_training_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='techniques',
            field=models.ManyToManyField(to='Techniques_Library.technique'),
        ),
    ]
